spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy?useUnicode=true&characterEncoding=UTF-8&assumeMinServerVersion=9.6
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
